networks:
  adi-network:
    driver: bridge

services:
  # Azure AI Translator
  azure-ai-translator:
    container_name: azure-ai-translator
    image: mcr.microsoft.com/azure-cognitive-services/translator/text-translation:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: 8
          memory: 42G
    environment:
      # Azure AI Translator settings
      EULA: accept # (REQUIRE)
      APIKEY: ${TRANSLATOR_KEY} # (REQUIRE)
      BILLING: ${TRANSLATOR_ENDPOINT_URI} # (REQUIRE)
      LANGUAGES: zh-Hant,zh-Hans,en,ja,id,es,fr,ru,vi,it,pt,de,ko,tr,da,he,fa,ms,th,fil,ar # (REQUIRE)
      MODEL_PATH: /usr/local/models # (REQUIRE) Path to language models, default is /usr/local/models
      HOTFIXDATAFOLDER: ""  # (Optional) Specify path if using Hotfix feature, leave empty by default
      GENERATEHOTFIXTEMPLATE: "false"  # (Optional) Set to true if you need to generate Hotfix template and specify HOTFIXDATAFOLDER, default is false
      DOWNLOADLICENSE: "false"  # (Optional) Set to true if you only want to download license file without starting the service, default is false
      Mounts:License: "" # (Optional) Specify path if using License feature, leave empty by default
      CATEGORIES: ""  # (Optional) Specify model categories if needed, leave empty by default
      MODSENVIRONMENT: ""  # (Optional) Specify MoDS endpoint if using MoDS service, leave empty by default
      MODELS: "" # (Optional) Leave empty by default
      TRANSLATORSYSTEMCONFIG: "" # (Optional) Leave empty by default
      # .Net Core settings
      Mounts:Output: /logs # (Optional) But there is no log in the container
      # Other settings
      ladurl: http://azure-ai-language:5000
      VISIONURL: http://azure-ai-read:5000
    volumes:
      - ./azure-ai-translator/models:/usr/local/models
      - ./azure-ai-translator/logs:/logs
    expose:
      - "5000"
    ports:
      - "5000:5000"
    networks:
      - adi-network

  # Azure AI Language
  azure-ai-language:
    container_name: azure-ai-language
    image: mcr.microsoft.com/azure-cognitive-services/textanalytics/language:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: 8
          memory: 24G
    environment:
      EULA: accept
      APIKEY: ${LANGUAGE_RESOURCE_KEY}
      BILLING: ${LANGUAGE_RESOURCE_ENDPOINT_URI}
    volumes:
      - ./azure-ai-language/output:/output
    expose:
      - "5000"
    ports:
      - "5001:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/status"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 120s
    networks:
      - adi-network

  # Azure AI Vision Read
  azure-ai-read:
    container_name: azure-ai-read
    image: mcr.microsoft.com/azure-cognitive-services/vision/read:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: 8
          memory: 24G
    environment:
      EULA: accept
      APIKEY: ${COMPUTER_VISION_KEY}
      BILLING: ${COMPUTER_VISION_ENDPOINT_URI}
    volumes:
      - ./azure-ai-read/share:/share
    expose:
      - "5000"
    ports:
      - "5002:5000"
    networks:
      - adi-network

