services:
  azure-ai-translator:
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: 2
  azure-ai-language:
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: 2
  azure-ai-read:
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: 2